### ISSUE TITLE
When do you plan to release the code? Thanks!

### ISSUE THREAD

**Issue by bernard0047** [robot0321/DepthRegularizedGS#1]

**Comment by robot0321** [comment]
@bernard0047 
Thank you for your interest!
Do you plan to compare with your method for a paper? or just want to evaluate?
Now I'm full of my hands, so I cannot ensure when it will be released. 
I will try to upload the code within this month.

**Comment by wtpro** [comment]
I would like run your code as a reference to my own work! We have very similar ideas!

**Comment by Eyoahz1243fei** [comment]
> @bernard0047 Thank you for your interest! Do you plan to compare with your method for a paper? or just want to evaluate? Now I'm full of my hands, so I cannot ensure when it will be released. I will try to upload the code within this month.

Do you have time to release the code soon? I'm looking forward to it!

**Comment by nandometzger** [comment]
+1 here.
I also want to include your work as a reference. How did you define the train-test split?

**Comment by robot0321** [comment]
I apologize for the delay. Now I upload the codes.
