### ISSUE TITLE
我想知道您是如何从稀疏深度得到稠密深度的，通过论文公式3和公式4

### ISSUE THREAD

**Issue by CUITCHENSIYU** [robot0321/DepthRegularizedGS#2]
您论文中有提到，首先通过SFM得到稀疏绝对深度，然后利用大模型得到一个可靠的相对深度，最后利用回归计算一个s和t去将相对深度转为绝对深度。您能提供下这部分的代码吗？谢谢。

**Comment by robot0321** [comment]
Please refer the recently uploaded code, Thanks.
