### ISSUE TITLE
Pytorch3D

### ISSUE THREAD

**Issue by umarkhalidAI** [robot0321/DepthRegularizedGS#5]
With your environment, I could only install pytorch3D==0.3.0. However, it gives error
`ImportError: cannot import name 'so3_exp_map' from 'pytorch3d.transforms.so3' `

**Comment by robot0321** [comment]
Thank you for noticing me, It will be solved if you update to the latest version of pytorch3d, (for example, ver 0.7.5)
I will revise the README and environment.yml file

**Comment by umarkhalidAI** [comment]
How would you install pytorch3D=0.7.5 with python 3.17?

**Comment by robot0321** [comment]
@umarkhalidAI 
You don't have to install pytorch3D=0.7.5, but a version that including `so3_exp_map()`
In my case, now I am using python=3.9.13, pytorch=1.13.0, pytorch3D=0.7.5
Sorry for the inconvenience.

**Comment by umarkhalidAI** [comment]
> @umarkhalidAI You don't have to install pytorch3D=0.7.5, but a version that including `so3_exp_map()` In my case, now I am using python=3.9.13, pytorch=1.13.0, pytorch3D=0.7.5 Sorry for the inconvenience.

yeah but your environment file says python 3.7.13

**Comment by bob-tinner** [comment]
@robot0321 Hi, I am facing issue same to @umarkhalidAI. Would you show me the revised environment.yml?

Like your comment, I tried on the environment below↓

```
name: DepthRegularizedGS
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - cudatoolkit=11.6
  - plyfile=0.8.1
  - python=3.9.13
  - pip=22.3.1
  - pytorch=1.13.0
  - torchaudio=0.13.0
  - torchvision=0.14.0
  - pytorch3d=0.7.5
  - tqdm
  - pip:
    - submodules/diff-gaussian-rasterization-depth-acc
    - submodules/simple-knn
```

but that didn't work fine. I would appreciate your reply.(sorry for clumsy English)

**Comment by RocketSumit** [comment]
Hi, you could install latest version using `pip install "git+https://github.com/facebookresearch/pytorch3d.git@stable"`.
